### ISSUE TITLE
init的时候， java.lang.NullPointerException

### ISSUE THREAD

**Issue by lzctbyong** [jpush/jshare-react-native#13]
` Caused by: java.lang.NullPointerException
                                                                             at cn.jiguang.b.a.b(Unknown Source)
                                                                             at cn.jiguang.b.a.a(Unknown Source)
                                                                             at cn.jiguang.api.JCoreInterface.init(Unknown Source)
                                                                             at cn.jiguang.share.android.api.JShareInterface.init(Unknown Source)
                                                                             at com.aim.weixiaoshenghuo.MainApplication.onCreate(MainApplication.java:87)`

**Comment by KenChoi1992** [comment]
有没有按照文档来，jcore 和 jshare 版本要匹配。可以看看 release 下的说明

**Comment by KenChoi1992** [comment]
@lzctbyong  这个问题没有回复就先关闭了。
