### ISSUE TITLE
cn.jiguang.share.wechat.b.a(Unknown Source)

### ISSUE THREAD

**Issue by swdenglian** [jpush/jshare-react-native#69]
## 环境
android： 7.0
jcore-react-native:：1.2.5
jshare-react-native：1.3.1
react：16.2.0
react-native：0.53.3
## 问题描述
调用 share 的时候弹出 “请稍后...”的转圈圈提示，然后瞬间又回来App,并未成功唤起微信
## RN 代码
```js
let shareParam = {
      platform: "wechat_session",
      type: "link",
      url: "https://www.baidu.com",
      imageUrl: "http://img.taopic.com/uploads/allimg/120727/201995-120HG1030762.jpg",
      title: " shared link",
      text: "the web link",
    };

    JShareModule.share(shareParam, (map: Object) => {
      console.log("share succeed, map: " + JSON.stringify(map));
    }, (map: Object) => {
      console.log("share failed, map: " + JSON.stringify(map));
});
```
## 错误提示
```
Chrome  console:
share failed, map: {"description":"Cannot find the description","state":"fail","code":-6}
```
```
Android Studio:
I/RCTJShareModule: share failed
W/System.err: java.lang.Throwable
W/System.err:     at cn.jiguang.share.android.api.AbsPlatform.notifyError(Unknown Source)
W/System.err:     at cn.jiguang.share.wechat.b.a(Unknown Source)
W/System.err:     at cn.jiguang.share.wechat.b.a(Unknown Source)
W/System.err:     at cn.jiguang.share.wechat.WeChatHandleActivity.onCreate(Unknown Source)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6915)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

### jpush 可以正常使用

我是android 小白也不清楚哪里配置错误了，求各位大大帮忙

**Comment by swdenglian** [comment]
微信重装就好了，之前是微信上“应用签名”写错了，然后重新安装了微信就可以分享了。。。
